X-Received: by 10.98.141.152 with SMTP id p24mr14398954pfk.41.1495652876530;
        Wed, 24 May 2017 12:07:56 -0700 (PDT)
X-BeenThere: singularity@lbl.gov
Received: by 10.36.107.87 with SMTP id v84ls2684959itc.12.gmail; Wed, 24 May
 2017 12:07:55 -0700 (PDT)
X-Received: by 10.99.186.21 with SMTP id k21mr41017075pgf.165.1495652875611;
        Wed, 24 May 2017 12:07:55 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1495652875; cv=none;
        d=google.com; s=arc-20160816;
        b=Si8ox82GnqAuEZa8/BTEhTJcpfPREOxeMv3evgQ6RLf170kO0YSzwzUFcX2dpzTvuI
         855VN0T2MyWNvcYDDTbR+DUw0VpUe6CufigjptuvwQ0KGVIgh3nwBtJNnhKu6X0Vx0+L
         dPDPg23NZNhYPyqsro/TsFyULCMBhGxtoUMyN4owCH0YsqrQg4tEoYF4CVmkkoUv3eGt
         SUt9DfDbX+A538vbbUqESo8IVOY3XVlSsbHRbZiZBekaFZd90/JjpR66WsuN3yvgAhcO
         6xExg4CiA0NgO9O7rVz23FPjiv68qRgRgnP7BpuNV1hU69EHktE6cL7aYn6tpSqUKbJh
         LzhA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:subject:message-id:date:from:references:in-reply-to:mime-version
         :dkim-signature:arc-authentication-results;
        bh=79OzQ1hASqmsyDRWZ9cQeJJyjrfxpZ5G5XeOHnJ6VLc=;
        b=xtqEPdEMhmsTLYGB8L/oS6dnCMGAcoyK0kkXqitKHE1/J+xdI2xtN/oBYHRfAe+7IV
         aP/92sYueT5QmjYTvl+WViXBeBN0wMBDs+qEMYfCjUftbksTZ3XfsCtBl5lzrVahQL/d
         AhZNWRo/psPgk5YPjQHyFHDRP3X2CZeflCDW5jM5hiSUFu1Ijqc2SBdC785L3dmWeYu3
         K59EKy9ZxQYZAKAoBL6LkIVHH9GlIHNSMLYBLSe4NfDe7iZqCylYcQL5anodHnNx3gxA
         59IAxQay3EbVxVKIQEV9lQj7bFMPur6ClgDTXCL1BKsVROsOZdpG5S64xEY9T4AikOSB
         XEiw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass head...@gmail.com;
       spf=pass (google.com: domain of vso...@gmail.com designates 209.85.217.193 as permitted sender) smtp.mailfrom=vso...@gmail.com
Return-Path: <vso...@gmail.com>
Received: from fe4.lbl.gov (fe4.lbl.gov. [128.3.41.71])
        by mx.google.com with ESMTP id 61si25059477plc.226.2017.05.24.12.07.55
        for <singu...@lbl.gov>;
        Wed, 24 May 2017 12:07:55 -0700 (PDT)
Received-SPF: pass (google.com: domain of vso...@gmail.com designates 209.85.217.193 as permitted sender) client-ip=209.85.217.193;
Authentication-Results: mx.google.com;
       dkim=pass head...@gmail.com;
       spf=pass (google.com: domain of vso...@gmail.com designates 209.85.217.193 as permitted sender) smtp.mailfrom=vso...@gmail.com
X-Ironport-SBRS: 3.4
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: =?us-ascii?q?A2FMAwB62CVZhsHZVdFZAx4GDBkGDIMBT?=
 =?us-ascii?q?AE+gQwHg2AIgTaaPXKPTYcEQyEBCoFvhAkCgmwHQxQBAQEBAQEBAQEBAQIQAQE?=
 =?us-ascii?q?BCAsLCCgvgjMFAgMaBgQERiEILgEBAQEBAQEBAQEBAQEBAQEBGQIrBAgZARoBA?=
 =?us-ascii?q?gIBIx0BCAUOHgMBCwYFCzcCAiEBAQ4DAQUBHA4HBAEcBIg1gTcBAw0IBQmgez+?=
 =?us-ascii?q?MB4IEBQEcgwoFg1wKGScNVoMqAQEBBwEBAQEBAQEZAgYSiCuCaDSCRRCBYBIBP?=
 =?us-ascii?q?SaCS4JgBYlAiESLZDuHIIcwhFiCW48cizInhEOCahQfgRU2YQ0zC3EVX4RPH4I?=
 =?us-ascii?q?LJDYHhw1HgWcBAQE?=
X-IronPort-AV: E=Sophos;i="5.38,387,1491289200"; 
   d="scan'208,217";a="75599748"
Received: from mail-ua0-f193.google.com ([209.85.217.193])
  by fe4.lbl.gov with ESMTP; 24 May 2017 12:07:44 -0700
Received: by mail-ua0-f193.google.com with SMTP id i46so12620116uaa.3
        for <singu...@lbl.gov>; Wed, 24 May 2017 12:07:44 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:in-reply-to:references:from:date:message-id:subject:to;
        bh=79OzQ1hASqmsyDRWZ9cQeJJyjrfxpZ5G5XeOHnJ6VLc=;
        b=oC2CKG1qrt9dgQw7oR+B1sB41NjBW1SsNcLTDoGrW0MnIW8ddNeoi96zQXXQiHOeaA
         p8R7ZgPnjzhqa1vP6p36IV4asoNOivQUiELSEZRvh+W8zbuhHngX3jhgeUraL9bMpFKb
         uFXB5jp9db7UkT7ABo4ottCXUh0t7wfUlpdJaeEDq742OZ4SvG8OzMltbRJyvHXEBZIM
         4ghD8fW9yoV+g+uiOE/BXIeJhAJZ5WAC9MLSIffWwr8E/wTwxL9lvWpjIKmnTg1u/bcY
         pMPql+1ot2rhnGlYdqR+BmKdRyzAdN6xggDyPzvManx2UCllR8hWQ1Y1KypLeWkql3Tq
         /s9g==
X-Gm-Message-State: AODbwcBcR4+I0iq2f3hUKx5mNJkzTOjVZTm3bgriZ8k0xS7aPAXZ9nb6
	mUODpIb9Jwhe9qMV1zfg0hTLpSL238w4
X-Received: by 10.176.69.65 with SMTP id r59mr19870576uar.80.1495652863428;
 Wed, 24 May 2017 12:07:43 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.103.48.143 with HTTP; Wed, 24 May 2017 12:07:22 -0700 (PDT)
In-Reply-To: <CA+KhMPsyKRrwZNrH_eeZpLZ-EXRdHfKMzdpUFj--g14gUUxAqg@mail.gmail.com>
References: <CA+KhMPsyKRrwZNrH_eeZpLZ-EXRdHfKMzdpUFj--g14gUUxAqg@mail.gmail.com>
From: vanessa s <vso...@gmail.com>
Date: Wed, 24 May 2017 15:07:22 -0400
Message-ID: <CAM=pu+JjS6G951+zb_OUaHizwjACjciWc-jz4yNjr6b-N6iZXg@mail.gmail.com>
Subject: Re: [Singularity] Conflicting modules b/w container and host
To: singularity@lbl.gov
Content-Type: multipart/alternative; boundary="94eb2c0b9898a21921055049d14a"

--94eb2c0b9898a21921055049d14a
Content-Type: text/plain; charset="UTF-8"

Hey Jerrin,

A few things come to mind:

- You can run the container with --contain or --cleanenv and then set paths
appropriately in the container environment
- sometimes it helps to call modules / files directly
- I would check the PYTHONPATH in the container right before running. You
should make sure the paths to the "old numpy" are not present

Maybe one of those things might help?

Best,

Vanessa

On Wed, May 24, 2017 at 2:47 PM, Jerrin Suresh <jerrin...@gmail.com>
wrote:

> Hi,
>
> I am facing a unique issue of conflicting python modules within the
> container as well as the one in the host machine. We have python 2.7.5
> installed within the container which has a numpy installation. Now if a
> user loads the python module on our HPC which is 2.7.8 which too has a
> numpy installation. The 'import numpy' fails within the container.
>
> ~~~~~~
> >>> import tensorflow as tf
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcurand.so locally
> ImportError: numpy.core.multiarray failed to import
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line
> 23, in <module>
>     from tensorflow.python import *
>   File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py",
> line 45, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py",
> line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py",
> line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname,
> description)
> ImportError: numpy.core.multiarray failed to import
> >>> import numpy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/__init__.py",
> line 180, in <module>
>     from . import add_newdocs
>   File "/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/add_newdocs.py",
> line 13, in <module>
>     from numpy.lib import add_newdoc
>   File "/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/__init__.py",
> line 8, in <module>
>     from .type_check import *
>   File "/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/lib/type_check.py",
> line 11, in <module>
>     import numpy.core.numeric as _nx
>   File "/N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/core/__init__.py",
> line 14, in <module>
>     from . import multiarray
> ImportError: /N/soft/cle4/python/2.7.8/lib/python2.7/site-packages/numpy/core/multiarray.so:
> undefined symbol: PyUnicodeUCS2_AsUTF8String
> >>>
> ~~~~~~
>
> This is how it works, when the host python module is unloaded
>
> ~~~~~~
> Singularity.tensorflow.img> python
> Python 2.7.5 (default, Nov  6 2016, 00:28:07)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> Could not open PYTHONSTARTUP
> IOError: [Errno 2] No such file or directory: '/etc/pythonstart'
> >>> import numpy
> >>> import tensorflow as tf
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
> library libcurand.so locally
> >>>
> ~~~~~~
>
> Regards,
> Jerrin
>
> --
> MS CS Fall-16
> Indiana University
> www.linkedin.com/in/jerrinsuresh
>
> --
> You received this message because you are subscribed to the Google Groups
> "singularity" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to singu...@lbl.gov.
>



-- 
Vanessa Villamia Sochat
Stanford University '16
(603) 321-0676

--94eb2c0b9898a21921055049d14a
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hey Jerrin,<div><br></div><div>A few things come to mind:<=
/div><div><br></div><div>- You can run the container with --contain or --cl=
eanenv and then set paths appropriately in the container environment</div><=
div>- sometimes it helps to call modules / files directly</div><div>- I wou=
ld check the PYTHONPATH in the container right before running. You should m=
ake sure the paths to the &quot;old numpy&quot; are not present</div><div><=
br></div><div>Maybe one of those things might help?</div><div><br></div><di=
v>Best,</div><div><br></div><div>Vanessa</div></div><div class=3D"gmail_ext=
ra"><br><div class=3D"gmail_quote">On Wed, May 24, 2017 at 2:47 PM, Jerrin =
Suresh <span dir=3D"ltr">&lt;<a href=3D"mailto:jerrin...@gmail.com" target=
=3D"_blank">jerrin...@gmail.com</a>&gt;</span> wrote:<br><blockquote class=
=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padd=
ing-left:1ex"><div dir=3D"ltr">Hi,<div><br></div><div>I am facing a unique =
issue of conflicting python modules within the container as well as the one=
 in the host machine. We have python 2.7.5 installed within the container w=
hich has a numpy=C2=A0installation. Now if a user loads the python module o=
n our HPC which is 2.7.8 which too has a numpy=C2=A0installation. The &#39;=
import numpy&#39; fails within the container.</div><div><br></div><div>~~~~=
~~</div><div><div><font size=3D"1">&gt;&gt;&gt; import tensorflow as tf=C2=
=A0</font></div><div><font size=3D"1">I tensorflow/stream_executor/<wbr>dso=
_loader.cc:105] successfully opened CUDA library libcublas.so locally</font=
></div><div><font size=3D"1">I tensorflow/stream_executor/<wbr>dso_loader.c=
c:105] successfully opened CUDA library libcudnn.so locally</font></div><di=
v><font size=3D"1">I tensorflow/stream_executor/<wbr>dso_loader.cc:105] suc=
cessfully opened CUDA library libcufft.so locally</font></div><div><font si=
ze=3D"1">I tensorflow/stream_executor/<wbr>dso_loader.cc:105] successfully =
opened CUDA library libcuda.so.1 locally</font></div><div><font size=3D"1">=
I tensorflow/stream_executor/<wbr>dso_loader.cc:105] successfully opened CU=
DA library libcurand.so locally</font></div><div><font size=3D"1">ImportErr=
or: numpy.core.multiarray failed to import</font></div><div><font size=3D"1=
">Traceback (most recent call last):</font></div><div><font size=3D"1">=C2=
=A0 File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;</font></div><=
div><font size=3D"1">=C2=A0 File &quot;/usr/lib/python2.7/site-<wbr>package=
s/tensorflow/__init__.<wbr>py&quot;, line 23, in &lt;module&gt;</font></div=
><div><font size=3D"1">=C2=A0 =C2=A0 from tensorflow.python import *</font>=
</div><div><font size=3D"1">=C2=A0 File &quot;/usr/lib/python2.7/site-<wbr>=
packages/tensorflow/python/__<wbr>init__.py&quot;, line 45, in &lt;module&g=
t;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 from tensorflow.python i=
mport pywrap_tensorflow</font></div><div><font size=3D"1">=C2=A0 File &quot=
;/usr/lib/python2.7/site-<wbr>packages/tensorflow/python/<wbr>pywrap_tensor=
flow.py&quot;, line 28, in &lt;module&gt;</font></div><div><font size=3D"1"=
>=C2=A0 =C2=A0 _pywrap_tensorflow =3D swig_import_helper()</font></div><div=
><font size=3D"1">=C2=A0 File &quot;/usr/lib/python2.7/site-<wbr>packages/t=
ensorflow/python/<wbr>pywrap_tensorflow.py&quot;, line 24, in swig_import_h=
elper</font></div><div><font size=3D"1">=C2=A0 =C2=A0 _mod =3D imp.load_mod=
ule(&#39;_pywrap_<wbr>tensorflow&#39;, fp, pathname, description)</font></d=
iv><div><font size=3D"1">ImportError: numpy.core.multiarray failed to impor=
t</font></div><div><font size=3D"1">&gt;&gt;&gt; import numpy=C2=A0</font><=
/div><div><font size=3D"1">Traceback (most recent call last):</font></div><=
div><font size=3D"1">=C2=A0 File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;=
module&gt;</font></div><div><font size=3D"1">=C2=A0 File &quot;/N/soft/cle4=
/python/2.7.8/<wbr>lib/python2.7/site-packages/<wbr>numpy/__init__.py&quot;=
, line 180, in &lt;module&gt;</font></div><div><font size=3D"1">=C2=A0 =C2=
=A0 from . import add_newdocs</font></div><div><font size=3D"1">=C2=A0 File=
 &quot;/N/soft/cle4/python/2.7.8/<wbr>lib/python2.7/site-packages/<wbr>nump=
y/add_newdocs.py&quot;, line 13, in &lt;module&gt;</font></div><div><font s=
ize=3D"1">=C2=A0 =C2=A0 from numpy.lib import add_newdoc</font></div><div><=
font size=3D"1">=C2=A0 File &quot;/N/soft/cle4/python/2.7.8/<wbr>lib/python=
2.7/site-packages/<wbr>numpy/lib/__init__.py&quot;, line 8, in &lt;module&g=
t;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 from .type_check import =
*</font></div><div><font size=3D"1">=C2=A0 File &quot;/N/soft/cle4/python/2=
.7.8/<wbr>lib/python2.7/site-packages/<wbr>numpy/lib/type_check.py&quot;, l=
ine 11, in &lt;module&gt;</font></div><div><font size=3D"1">=C2=A0 =C2=A0 i=
mport numpy.core.numeric as _nx</font></div><div><font size=3D"1">=C2=A0 Fi=
le &quot;/N/soft/cle4/python/2.7.8/<wbr>lib/python2.7/site-packages/<wbr>nu=
mpy/core/__init__.py&quot;, line 14, in &lt;module&gt;</font></div><div><fo=
nt size=3D"1">=C2=A0 =C2=A0 from . import multiarray</font></div><div><font=
 size=3D"1">ImportError: /N/soft/cle4/python/2.7.8/lib/<wbr>python2.7/site-=
packages/numpy/<wbr>core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsU=
TF8String</font></div><div><font size=3D"1">&gt;&gt;&gt;=C2=A0</font></div>=
</div><div>~~~~~~</div><div><br></div><div>This is how it works, when the h=
ost python module is unloaded<br></div><div><br></div><div>~~~~~~</div><div=
><div><font size=3D"1">Singularity.tensorflow.img&gt; python=C2=A0</font></=
div><div><font size=3D"1">Python 2.7.5 (default, Nov =C2=A06 2016, 00:28:07=
)=C2=A0</font></div><div><font size=3D"1">[GCC 4.8.5 20150623 (Red Hat 4.8.=
5-11)] on linux2</font></div><div><font size=3D"1">Type &quot;help&quot;, &=
quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more i=
nformation.</font></div><div><font size=3D"1">Could not open PYTHONSTARTUP<=
/font></div><div><font size=3D"1">IOError: [Errno 2] No such file or direct=
ory: &#39;/etc/pythonstart&#39;</font></div><div><font size=3D"1">&gt;&gt;&=
gt; import numpy=C2=A0</font></div><div><font size=3D"1">&gt;&gt;&gt; impor=
t tensorflow as tf</font></div><div><font size=3D"1">I tensorflow/stream_ex=
ecutor/<wbr>dso_loader.cc:105] successfully opened CUDA library libcublas.s=
o locally</font></div><div><font size=3D"1">I tensorflow/stream_executor/<w=
br>dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally<=
/font></div><div><font size=3D"1">I tensorflow/stream_executor/<wbr>dso_loa=
der.cc:105] successfully opened CUDA library libcufft.so locally</font></di=
v><div><font size=3D"1">I tensorflow/stream_executor/<wbr>dso_loader.cc:105=
] successfully opened CUDA library libcuda.so.1 locally</font></div><div><f=
ont size=3D"1">I tensorflow/stream_executor/<wbr>dso_loader.cc:105] success=
fully opened CUDA library libcurand.so locally</font></div><div><font size=
=3D"1">&gt;&gt;&gt;=C2=A0</font></div><div>~~~~~~</div><div><br></div><div>=
Regards,</div><div>Jerrin</div><span class=3D"HOEnZb"><font color=3D"#88888=
8"><div><br></div>-- <br><div class=3D"m_-1108505852489272235gmail_signatur=
e"><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div>MS CS Fall-16<br></div>=
<div>Indiana University<br><span><span><a href=3D"http://www.linkedin.com/i=
n/" target=3D"_blank">www.linkedin.com/in/</a></span><span>jerrinsure<wbr>s=
h</span></span><br></div><div dir=3D"ltr"><div><div><br></div></div></div><=
/div></div></div></div></div>
</font></span></div></div><span class=3D"HOEnZb"><font color=3D"#888888">

<p></p>

-- <br>
You received this message because you are subscribed to the Google Groups &=
quot;singularity&quot; group.<br>
To unsubscribe from this group and stop receiving emails from it, send an e=
mail to <a href=3D"mailto:singu...@lbl.gov" target=3D"_blank">singularity+u=
nsubscribe@lbl.<wbr>gov</a>.<br>
</font></span></blockquote></div><br><br clear=3D"all"><div><br></div>-- <b=
r><div class=3D"gmail_signature" data-smartmail=3D"gmail_signature">Vanessa=
 Villamia Sochat<br>Stanford University &#39;16<br><div><div><div>(603) 321=
-0676</div></div></div></div>
</div>

--94eb2c0b9898a21921055049d14a--
