Date: Thu, 9 Nov 2017 05:36:30 -0800 (PST)
From: Christophe Trophime <christ...@googlemail.com>
To: singularity <singu...@lbl.gov>
Message-Id: <99b6aa03-9433-4fc9-ad93-9d1daaa861ff@lbl.gov>
Subject: singularity-container 2.3.2-1: import BIG dockerimage fails
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_468_1172159272.1510234590322"

------=_Part_468_1172159272.1510234590322
Content-Type: multipart/alternative; 
	boundary="----=_Part_469_189975581.1510234590322"

------=_Part_469_189975581.1510234590322
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Hi,
trying to create a singularity container on Debian/Testing (actually 
singularity-container 2.3.2-1)
from a large docker image I got the following error:

+ docker images feelpp/hifimagnet:develop-yakkety --format '{{.Size}}'
feelpp/hifimagnet:develop-yakkety: 10.8 GB
+ /usr/bin/singularity create --size 12083 hifimagnet-develop-yakkety.img
Initializing Singularity image subsystem
Opening image file: hifimagnet-develop-yakkety.img
Creating 12083MiB image
Binding image to loop
Creating file system within image
Image is done: hifimagnet-develop-yakkety.img
+ /usr/bin/singularity import hifimagnet-develop-yakkety.img 
docker://feelpp/hifimagnet:develop-yakkety
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/singularity/python/import.py", line 107, 
in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/import.py", line 83, 
in main
    layerfile=LAYERFILE)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/docker/main.py", line 
82, in IMPORT
    client = DockerApiConnection(image=image,auth=auth)
...
RuntimeError: maximum recursion depth exceeded while calling a Python object
+ sudo /usr/bin/singularity bootstrap hifimagnet-develop-yakkety.img 
hifimagnet-docker.def
Sanitizing environment


Any idea of what I did wrong?
Best

------=_Part_469_189975581.1510234590322
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi,<div>trying to create a singularity container on Debian=
/Testing (actually singularity-container 2.3.2-1)<br>from a large docker im=
age I got the following error:<br><br></div><div><div>+ docker images feelp=
p/hifimagnet:develop-yakkety --format &#39;{{.Size}}&#39;</div><div>feelpp/=
hifimagnet:develop-yakkety: 10.8 GB<br></div><div>+ /usr/bin/singularity cr=
eate --size 12083 hifimagnet-develop-yakkety.img<br></div><div>Initializing=
 Singularity image subsystem</div><div>Opening image file: hifimagnet-devel=
op-yakkety.img</div><div>Creating 12083MiB image</div><div>Binding image to=
 loop</div><div>Creating file system within image</div><div>Image is done: =
hifimagnet-develop-yakkety.img</div><div>+ /usr/bin/singularity import hifi=
magnet-develop-yakkety.img docker://feelpp/hifimagnet:develop-yakkety</div>=
<div>Traceback (most recent call last):</div></div><div><div>=C2=A0 File &q=
uot;/usr/lib/x86_64-linux-gnu/singularity/python/import.py&quot;, line 107,=
 in &lt;module&gt;</div><div>=C2=A0 =C2=A0 main()</div><div>=C2=A0 File &qu=
ot;/usr/lib/x86_64-linux-gnu/singularity/python/import.py&quot;, line 83, i=
n main</div><div>=C2=A0 =C2=A0 layerfile=3DLAYERFILE)</div><div>=C2=A0 File=
 &quot;/usr/lib/x86_64-linux-gnu/singularity/python/docker/main.py&quot;, l=
ine 82, in IMPORT</div><div>=C2=A0 =C2=A0 client =3D DockerApiConnection(im=
age=3Dimage,auth=3Dauth)</div></div><div>...</div><div>RuntimeError: maximu=
m recursion depth exceeded while calling a Python object</div><div>+ sudo /=
usr/bin/singularity bootstrap hifimagnet-develop-yakkety.img hifimagnet-doc=
ker.def</div><div>Sanitizing environment</div><div><br></div><div><br></div=
><div>Any idea of what I did wrong?</div><div>Best</div></div>
------=_Part_469_189975581.1510234590322--

------=_Part_468_1172159272.1510234590322--
